---

- hosts: all
  gather_facts: false
  become: true

  vars:
    vg_lookup: "rootvg" # ignores case

  tasks:

    - name: Stop AuditD
      service:
        name: auditd
        state: stopped

    - name: Delete existing log files
      command: rm -r -f /var/log/audit/*      
    
    - name: Determine VG name
      command: "vgs | grep -i {{ vg_lookup }} | awk {'print $1'}"
      register: vg_name_result

    - name: Create Audit Log Volume on rootvg
      community.general.lvol:
        vg: "{{ vg_name_result.stdout_lines[0] }}"
        lv: auditvol
        size: 150

    - name: Create filesystem
      filesystem:
        fstype: xfs
        dev: /dev/mapper/rhel-auditvol

    - name: Create fstab entry
      lineinfile: 
        dest: /etc/fstab
        backup: yes
        state: present
        line: "/dev/mapper/rhel-auditvol   /var/log/audit                       xfs     defaults        0 0"

    - name: Mount Audit Filesystem
      mount:
        path: /var/log/audit
        src: /dev/mapper/rhel-auditvol
        fstype: xfs
        state: mounted

    - name: Start AuditD
      service:
        name: auditd
        state: started
