---

- hosts: all
  tasks:

  - name: Make backup copies of files
    copy:
      src: /etc/pam.d/system-auth
      dest: /etc/pam.d/system-auth-local
  - name:
    copy:
      src: /etc/pam.d/password-auth
      dest: /etc/pam.d/password-auth-local

  - name: Set System Auth PAM Entries
    lineinfile:
      path: /etc/pam.d/system-auth
      regexp: '^password    requisite     pam_cracklib.so'
      line: 'password    requisite     pam_cracklib.so try_first_pass retry=3 minlen=15 dcredit=-1 ucredit=-1 ocredit=-1 lecredit=-1'

#  - name: Set Password Auth PAM entries
#    lineinfile:
#      path: /etc/pam.d/password-auth-local
#      regexp: '^auth        sufficient    pam_unix.so nullok try_first_pass'
#      line: 'auth        [success=1 default=bad]    pam_unix.so'
#  - name: Set Password Auth faillock.so
#    lineinfile:
#      path: /etc/pam.d/password-auth-local
#      line: 'auth required pam_faillock.so preauth audit silent deny=5 unlock_time=900'
#      insertbefore: 'auth [success=1 default=bad] pam_unix.so'

  - name: Create symbolic links
    file:
      src: /etc/pam.d/system-auth-local
      dest: /etc/pam.d/system-auth
      state: link
  - name:
    file:
      src: /etc/pam.d/password-auth-local
      dest: /etc/pam.d/password-auth
      state: link

